# Generated by Django 4.2.13 on 2025-04-08 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherPortal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('returned', 'Returned for Revision')], default='draft', max_length=20),
        ),
    ]
