# Generated by Django 4.2.13 on 2025-04-12 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherPortal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradecomment',
            name='grade',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.DeleteModel(
            name='GradeComment',
        ),
    ]
