# Generated by Django 4.2.13 on 2025-03-21 08:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherPortal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddField(
            model_name='grade',
            name='course',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='grade',
            name='grade',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='grade',
            name='quarter',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='grade',
            name='school_year',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='grade',
            name='student',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='grade',
            name='teacher',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='grade',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
