# Generated by Django 4.2.13 on 2025-04-30 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherPortal', '0002_remove_gradecomment_grade_delete_grade_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SchoolForm',
        ),
    ]
