# Generated by Django 4.2.13 on 2025-03-21 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherPortal', '0002_alter_grade_options_grade_course_grade_grade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='course',
        ),
    ]
