# Generated by Django 4.2.13 on 2025-04-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherPortal', '0002_alter_grade_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('returned', 'Returned for Revision')], default='draft', max_length=20, null=True),
        ),
    ]
