# Generated by Django 4.2.13 on 2025-04-11 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherPortal', '0004_alter_gradecomment_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('enrollment', 'Enrollment'), ('grades', 'Grades'), ('attendance', 'Attendance'), ('financial', 'Financial'), ('other', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to='school_forms/')),
                ('file_type', models.CharField(blank=True, max_length=50)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('uploaded_by', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('school_year', models.CharField(blank=True, max_length=20, null=True)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('downloads', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-date_uploaded'],
            },
        ),
        migrations.AlterField(
            model_name='gradecomment',
            name='author',
            field=models.CharField(max_length=100),
        ),
    ]
