# Generated by Django 4.2.13 on 2025-04-11 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_increase_school_year_length'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GradeComment',
        ),
    ]
