# Generated by Django 4.2.13 on 2025-03-19 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sections',
            name='subject',
        ),
    ]
