# Generated by Django 4.2.13 on 2025-04-10 01:00

from django.db import migrations, models
from django.core.validators import MinValueValidator, MaxValueValidator
import django.utils.timezone
import django.db.models.deletion
from decimal import Decimal


def migrate_grades_data(apps, schema_editor):
    # Get the old and new models
    OldGrades = apps.get_model('dashboard', 'Grades')
    NewGrades = apps.get_model('dashboard', 'NewGrades')
    
    # Copy data from old table to new table
    for old_grade in OldGrades.objects.all():
        NewGrades.objects.create(
            student=old_grade.student,
            subject=old_grade.subject,
            teacher=old_grade.teacher,
            grade=old_grade.grade,
            quarter=old_grade.quarter,
            school_year=old_grade.school_year,
            status=old_grade.status or 'draft',
            remarks=old_grade.remarks,
            date_created=old_grade.date_created,
            date_modified=old_grade.date_modified,
            date_submitted=old_grade.date_submitted,
            date_approved=old_grade.date_approved,
            uploaded_at=old_grade.uploaded_at or django.utils.timezone.now()
        )


def reverse_migrate(apps, schema_editor):
    # This is a destructive migration, so we'll leave this empty
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherPortal', '0001_initial'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        # Create new table with correct structure
        migrations.CreateModel(
            name='NewGrades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[
                    django.core.validators.MinValueValidator(0), 
                    django.core.validators.MaxValueValidator(100)
                ])),
                ('quarter', models.CharField(choices=[
                    ('1', 'First Quarter'),
                    ('2', 'Second Quarter'),
                    ('3', 'Third Quarter'),
                    ('4', 'Fourth Quarter')
                ], max_length=2)),
                ('school_year', models.CharField(max_length=20)),
                ('status', models.CharField(blank=True, choices=[
                    ('draft', 'Draft'),
                    ('submitted', 'Submitted'),
                    ('approved', 'Approved'),
                    ('returned', 'Returned for Revision')
                ], default='draft', max_length=20, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_submitted', models.DateTimeField(blank=True, null=True)),
                ('date_approved', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey('dashboard.Student', on_delete=models.CASCADE, related_name='new_grades')),
                ('subject', models.ForeignKey('dashboard.Subject', on_delete=models.CASCADE)),
                ('teacher', models.ForeignKey('dashboard.Teachers', on_delete=models.CASCADE)),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
                'ordering': ['-date_created'],
                'unique_together': {('student', 'subject', 'teacher', 'quarter', 'school_year')},
            },
        ),
        # Run the data migration
        migrations.RunPython(migrate_grades_data, reverse_migrate),
        # Delete the old table
        migrations.DeleteModel(name='Grades'),
        # Rename the new table to the original name
        migrations.RenameModel(old_name='NewGrades', new_name='Grades'),
        # Update the related_name on student field to match original
        migrations.AlterField(
            model_name='Grades',
            name='student',
            field=models.ForeignKey('dashboard.Student', on_delete=models.CASCADE, related_name='grades'),
        ),
    ]
