# Generated by Django 4.2.13 on 2025-04-12 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_grades_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='school_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.schoolyear'),
        ),
    ]
