# Generated by Django 4.2.13 on 2025-03-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_sections_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='school_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
