# Generated by Django 4.2.13 on 2025-04-24 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0004_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_type', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('enrollment', 'Enrollment'), ('grade', 'Grade'), ('section', 'Section'), ('schedule', 'Schedule'), ('event', 'Event')], max_length=20)),
                ('school_year', models.CharField(max_length=20)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['archive_type', 'school_year'], name='dashboard_a_archive_52fad6_idx')],
            },
        ),
    ]
