# Generated by Django 4.2.13 on 2025-04-10 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_sync_teacher_portal_grades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='school_year',
            field=models.CharField(max_length=50),
        ),
    ]
