# Generated by Django 4.2.13 on 2025-04-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_schoolform_teacherform_formsubmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherform',
            name='form',
        ),
        migrations.RemoveField(
            model_name='teacherform',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='schoolform',
            name='file',
            field=models.FileField(upload_to='forms/%Y/%m/%d/'),
        ),
        migrations.DeleteModel(
            name='FormSubmission',
        ),
        migrations.DeleteModel(
            name='TeacherForm',
        ),
    ]
