# Generated by Django 4.2.13 on 2025-04-26 15:30

import dashboard.forms_models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0008_remove_teacherform_form_remove_teacherform_teacher_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolform',
            options={'ordering': ['-date_uploaded']},
        ),
        migrations.AlterField(
            model_name='schoolform',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='schoolform',
            name='file',
            field=models.FileField(upload_to=dashboard.forms_models.form_upload_path),
        ),
        migrations.AlterField(
            model_name='schoolform',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='schoolform',
            name='uploaded_by',
            field=models.CharField(max_length=150),
        ),
        migrations.CreateModel(
            name='TeacherForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('date_assigned', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.schoolform')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_assigned'],
                'unique_together': {('teacher', 'form')},
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_file', models.FileField(upload_to='form_submissions/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('feedback', models.TextField(blank=True)),
                ('submitted_date', models.DateTimeField(auto_now_add=True)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL)),
                ('teacher_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.teacherform')),
            ],
            options={
                'ordering': ['-submitted_date'],
            },
        ),
    ]
