# Generated by Django 4.2.13 on 2025-03-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_schedules_day_alter_schedules_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedules',
            name='day',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='schedules',
            name='grade_level',
            field=models.IntegerField(),
        ),
    ]
