# Generated by Django 4.2.13 on 2025-03-30 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_schedules_day_alter_schedules_grade_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sections',
            name='grade_level',
            field=models.IntegerField(),
        ),
    ]
