# Generated by Django 4.2.13 on 2025-04-02 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_sections_grade_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Withdrawn', 'Withdrawn'), ('Completed', 'Completed'), ('Dropped', 'Dropped'), ('Transferred', 'Transferred')], default='Active', max_length=20),
        ),
    ]
