# Generated by Django 4.2.13 on 2025-04-02 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_enrollment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferredStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateField(auto_now_add=True)),
                ('transfer_school', models.CharField(max_length=255)),
                ('reason', models.TextField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_details', to='dashboard.enrollment')),
            ],
        ),
        migrations.CreateModel(
            name='DroppedStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drop_date', models.DateField(auto_now_add=True)),
                ('reason', models.TextField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dropped_details', to='dashboard.enrollment')),
            ],
        ),
        migrations.CreateModel(
            name='CompletedStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_date', models.DateField(auto_now_add=True)),
                ('final_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completion_details', to='dashboard.enrollment')),
            ],
        ),
    ]
