# Generated by Django 4.2.13 on 2025-05-09 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_event_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registrar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.schoolyear')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registrar_role', to='dashboard.teachers')),
            ],
        ),
    ]
