# Generated by Django 4.2.13 on 2025-04-03 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_transferredstudent_droppedstudent_completedstudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('Not Enrolled', 'Not Enrolled'), ('Enrolled', 'Enrolled'), ('Transferred', 'Transferred'), ('Dropped', 'Dropped'), ('Completed', 'Completed')], default='Not Enrolled', max_length=20),
        ),
    ]
