# Generated by Django 4.2.13 on 2025-05-10 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_registrar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrar',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrar_role', to='dashboard.teachers'),
        ),
    ]
