# Generated by Django 4.2.13 on 2025-04-03 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_adminactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade9Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year', models.CharField(max_length=20)),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Withdrawn', 'Withdrawn'), ('Completed', 'Completed'), ('Dropped', 'Dropped'), ('Transferred', 'Transferred')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade9_enrollments', to='dashboard.sections')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade9_enrollments', to='dashboard.student')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('student', 'section', 'school_year')},
            },
        ),
        migrations.CreateModel(
            name='Grade8Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year', models.CharField(max_length=20)),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Withdrawn', 'Withdrawn'), ('Completed', 'Completed'), ('Dropped', 'Dropped'), ('Transferred', 'Transferred')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade8_enrollments', to='dashboard.sections')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade8_enrollments', to='dashboard.student')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('student', 'section', 'school_year')},
            },
        ),
        migrations.CreateModel(
            name='Grade12Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.CharField(max_length=20)),
                ('school_year', models.CharField(max_length=20)),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Withdrawn', 'Withdrawn'), ('Completed', 'Completed'), ('Dropped', 'Dropped'), ('Transferred', 'Transferred')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade12_enrollments', to='dashboard.sections')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade12_enrollments', to='dashboard.student')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('student', 'section', 'school_year')},
            },
        ),
        migrations.CreateModel(
            name='Grade11Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.CharField(max_length=20)),
                ('school_year', models.CharField(max_length=20)),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Withdrawn', 'Withdrawn'), ('Completed', 'Completed'), ('Dropped', 'Dropped'), ('Transferred', 'Transferred')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade11_enrollments', to='dashboard.sections')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade11_enrollments', to='dashboard.student')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('student', 'section', 'school_year')},
            },
        ),
        migrations.CreateModel(
            name='Grade10Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year', models.CharField(max_length=20)),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Withdrawn', 'Withdrawn'), ('Completed', 'Completed'), ('Dropped', 'Dropped'), ('Transferred', 'Transferred')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade10_enrollments', to='dashboard.sections')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade10_enrollments', to='dashboard.student')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('student', 'section', 'school_year')},
            },
        ),
    ]
