# Generated by Django 4.2.13 on 2025-05-13 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_registrar_assigned_by_registrar_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transferee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transferee_record', to='dashboard.enrollment')),
            ],
        ),
        migrations.CreateModel(
            name='Returnee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='returnee_record', to='dashboard.enrollment')),
            ],
        ),
    ]
