# Generated by Django 4.2.13 on 2025-04-03 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_grade9enrollment_grade8enrollment_grade12enrollment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sections',
            options={'ordering': ['grade_level', 'section_id'], 'verbose_name_plural': 'Sections'},
        ),
        migrations.AlterField(
            model_name='sections',
            name='adviser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.teachers'),
        ),
    ]
