# Generated by Django 4.2.13 on 2025-05-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_remove_returnee_enrollment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
