# Generated by Django 4.2.13 on 2025-04-04 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_schoolyear'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolyear',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='schoolyear',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='schoolyear',
            name='is_previous',
            field=models.BooleanField(default=False),
        ),
    ]
