# Generated by Django 4.2.13 on 2025-05-13 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='teacher',
        ),
    ]
