# Generated by Django 4.2.13 on 2025-05-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_remove_feedback_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='force_password_change',
            field=models.BooleanField(default=True),
        ),
    ]
