# Generated by Django 4.2.13 on 2025-05-28 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_teachers_force_password_change'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('new_grade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reason', models.TextField()),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.teachers')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='dashboard.grades')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
